### ISSUE TITLE
For future SEO  integrations 

### ISSUE THREAD

**Issue by reslear** [s00d/nuxt-i18n-micro#11]
For the future, we should consider implementing two-way integration for SEO, particularly with tools like the Nuxt Sitemap module (https://github.com/nuxt-modules/sitemap). Have you explored that option yet?

**Comment by s00d** [comment]
In principle, I can try to create the sitemap myself using a new plugin for my module. I don't really want to integrate something into other people's modules right now, as it would take too much time.

**Comment by reslear** [comment]
Maybe [harlan-zw](https://github.com/harlan-zw) should pay attention to the fact that api can be universal in the future

**Comment by harlan-zw** [comment]
The config API looks identical, they even share the same config key, so this can be supported without any effort, unless there are some specific behavior quirks that I should know about.

Please review: https://github.com/nuxt-modules/sitemap/pull/357

**Comment by s00d** [comment]
> The config API looks identical, they even share the same config key, so this can be supported without any effort, unless there are some specific behavior quirks that I should know about.
> 
> Please review: [nuxt-modules/sitemap#357](https://github.com/nuxt-modules/sitemap/pull/357)

Unfortunately, only the config looks almost the same, except for the strategy, which I specifically renamed because in my case, there aren't multiple strategies, just a parameter called `includeDefaultLocaleRoute`. 
- `true` - no prefix
- `false` - prefix

Inside, unfortunately, everything differs greatly. I looked at your code, and as far as I can see, you modify `locales` in the config, whereas my module uses a different `locales` structure; it contains an object:
```javascript
export interface Locale {
  code: string
  disabled?: boolean
  iso?: string
  dir?: 'ltr' | 'rtl' | 'auto'
}
```

I didn’t go further into how your sitemap is generated, but most likely you somehow refer to routes. In my module, the routing structure is entirely changed to regex. 
So, the routes can be of two formats:
1. Without locale, for example: `/page`
2. With locale: `/:locales(en|de)/page`

In principle, I can rename `includeDefaultLocaleRoute` to `strategy`; it’s not that critical. However, everything else cannot be changed, as it's essentially the reason why I developed the entire module.

**Comment by harlan-zw** [comment]
I wouldn't be concerned about minor differences as the config can be normalized.

Are you modifying the underlying Vue Router routing? If not then it should _just work_.

**Comment by harlan-zw** [comment]
Hmm I was not able to replicate that so not too sure. 

In terms of moving this along, I'm happy in either direction, merging or not, just thought it was an interesting proof of concept. I would hope if it was merged that you would support me in maintenance of any code related to the integration, which, may not interest you.

Will leave it to you to decide on next steps.

**Comment by s00d** [comment]
@harlan-zw Let's try to merge it, and I will continue to investigate any potential issues afterward.

**Comment by harlan-zw** [comment]
Merged in 6.1.0 :+1:

**Comment by s00d** [comment]
Regarding integrations, I connected my module for generating documentation from OpenAPI: https://github.com/on-org/nuxt-openapi-docs-module/commit/eca9fcc06bed428fae0833b58b716d08255e81af. It can generally be used as an example, although there are still a few things I'd like to adjust.

**Comment by s00d** [comment]
@harlan-zw 

Hello,

I’ve gotten around to testing, and overall, the module works, but it currently only generates routes for the default locale. The issue is that my module handles route generation differently. For multiple locales, it creates a single route, for example:

`/:locale(de|ja)/page`

So it bundles all locales into one route, which prevents large bundles from being created, unlike in i18n. In order for everything to work properly, the `deepForEachPage` method needs to be adjusted.

Here’s a possible solution:

```javascript
function deepForEachPage(pages, callback, routesNameSeparator, fullpath = null, depth = 0) {
  pages.forEach((page) => {
    let currentPath;
    if (page.path.startsWith("/")) {
      currentPath = page.path;
    } else {
      currentPath = page.path === "" ? fullpath : `${fullpath.replace(/\/$/, "")}/${page.path}`;
    }

    const localePattern = /\/:locale\(([^)]+)\)/;
    const match = localePattern.exec(currentPath);


    if (match) {
      const locales = match[1].split("|");
      locales.forEach((locale) => {
        let subPage = { ...page };
        const localizedPath = currentPath.replace(localePattern, `/${locale}`);
        subPage.name += routesNameSeparator + locale
        subPage.path = localizedPath
        callback(subPage, localizedPath || "", depth);
      });
    } else {
      callback(page, currentPath || "", depth);
    }

    if (page.children) {
      deepForEachPage(page.children, callback, routesNameSeparator, currentPath, depth + 1);
    }
  });
}
```

In this implementation, if the route contains `:locale`, it extracts the locale from the route and converts the routes into a default format similar to i18n. I’ve added a `routesNameSeparator` to the method to handle naming.

I didn’t create a pull request since it’s probably better for you to review how this should be properly integrated.

**Comment by s00d** [comment]
Everything should be working now. If there are any issues with the new customRegexMatcher option, I have a rough idea of how to fix it, but I’m currently swamped with work. Maybe someone else can address this issue. For now, I’m closing the issue. We've created examples, so I believe anyone who needs it will be able to figure it out. I’ve also tested the hooks, and everything is working fine.
