### ISSUE TITLE
middleware/i18n-redirect.ts is very agressive

### ISSUE THREAD

**Issue by tirojal** [s00d/nuxt-i18n-micro#24]
When includeDefaultLocaleRoute === 'true'  `middleware/i18n-redirect.ts`  is forcing redirect for unlocalized routes and server endpoints.

I think we should care about redirection to default locale in the plugin
The logic is already written in 03.define.ts  ~ line 32  ~ useRouter().beforeEach(...), we only need to execute it on server side immediately

**Comment by s00d** [comment]
Alright, let's proceed as you suggested. I've updated to version v1.20.4, completely removed the server middleware, and moved the logic to the `define` function.

However, I must point out that since the data is also required on the client side, `globalLocaleRoutes` will now be passed to the client.

I’ve written a couple of tests, and everything seems to be working as expected.

**Comment by tirojal** [comment]
> However, I must point out that since the data is also required on the client side, globalLocaleRoutes will now be passed to the client.

You can just check if route exsits with `router.has(defaultRouteName )` instead of loading globalLocaleRoutes to client

**Comment by tirojal** [comment]
/\ /\ also it will allow to use it with 
```js
$defineI18nRoute({
  localeRoutes: false
}}
```

**Comment by tirojal** [comment]
@s00d I updated my comment about `globalLocaleRoutes` passed to the client. https://github.com/s00d/nuxt-i18n-micro/issues/24#issuecomment-2379368399

**Comment by s00d** [comment]
Yes, you're right, and there's less logic now. Thank you, I've updated to v1.20.5.
